Add serialization and deserialization support to BKTree
eugene-bulkin/rust-bk-tree pull request #17
Opened 2023-02-06 01:23 UTC by johnDeSilencio

This PR changes the structs `BKNode`, `BKTree`, and `Levenshtein` to all derive from `serde`'s `Serialize` and `Deserialize` traits. Tests have been added to confirm that a BKTree that has been serialized and deserialized retains is equivalent to before those operations.

2023-03-16 17:55 UTC, johnDeSilencio commented
@eugene-bulkin Looking forward to your feedback on this!

2023-03-16 19:09 UTC, eugene-bulkin requested changes
Can we just change the name of the feature to `serde`? Otherwise looks fine!

2023-03-17 05:57 UTC, johnDeSilencio commented
> Can we just change the name of the feature to `serde`? Otherwise looks fine!

Absolutely! Pushed a commit to change the feature name from `serde-support` to just `serde`

2023-03-17 14:45 UTC, eugene-bulkin approved these changes

2023-03-17 14:45 UTC, merged